/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import hospitalsystem.*;
import hospitalsystem.Data;
import java.awt.ComponentOrientation;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import net.proteanit.sql.DbUtils;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author m.amin
 */
public class Specialties extends javax.swing.JFrame {

    String Query = "SELECT Specialties.id as [الكود], Specialties.Job_id, JOBS.JOB_NAME as [الوظيفة], Specialties.Special_name "
            + "as [التخصص] FROM JOBS INNER JOIN Specialties ON JOBS.ID = Specialties.Job_id  WHERE  Specialties.I=0 and JOBS.I=0";
    int Specialtiesid = 0;
    DefaultComboBoxModel data = new DefaultComboBoxModel();
    DefaultComboBoxModel data2 = new DefaultComboBoxModel();

    /**
     * Creates new form Clinics
     */
    private static Specialties obj = null;

    private Specialties() {
        initComponents();
        this.setTitle("التخصصات");
        this.setLocationRelativeTo(null);
        Image icon = Toolkit.getDefaultToolkit().getImage(".\\src\\images\\icon.gif");
        this.setIconImage(icon);
        this.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        this.jTextField1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        this.jTable1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        this.btnedite.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        this.btnSave.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        this.btndelete.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        this.jLabel1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        ((JLabel)jComboBox1.getRenderer()).setHorizontalAlignment(JLabel.RIGHT);
        this.jComboBox2.show(false);
        refrishtable();
        btnedite.setEnabled(false);
        btndelete.setEnabled(false);
        fillcombobox();
        //AutoCompleteDecorator.decorate(jComboBox1);

    }

    public static Specialties getObj() {
        if (obj == null) {
            obj = new Specialties();
        }
        return obj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnedite = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnnew = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(207, 221, 238));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowGrid(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("التخصص");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(0, 0, 255));
        btnSave.setText("حفظ");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btndelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btndelete.setForeground(new java.awt.Color(0, 0, 255));
        btndelete.setText("حذف");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnedite.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnedite.setForeground(new java.awt.Color(0, 0, 255));
        btnedite.setText("تعديل");
        btnedite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnediteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("لتعديل او حذف تخصص قم باختياره من الجدول");

        btnnew.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnnew.setForeground(new java.awt.Color(0, 0, 255));
        btnnew.setText("جديد");
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("الوظيفة");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setEnabled(false);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btndelete)
                                .addGap(27, 27, 27)
                                .addComponent(btnSave)
                                .addGap(18, 18, 18)
                                .addComponent(btnedite)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnnew))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)))
                        .addGap(69, 69, 69))))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnedite, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnew, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Clinics");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if (jTextField1.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "ادخل التخصص", "خطأ", JOptionPane.ERROR_MESSAGE);
        } else {
            Save_Data();
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        String val = jTable1.getModel().getValueAt(row, 3).toString();
        String jobid = jTable1.getModel().getValueAt(row, 1).toString();
        jTextField1.setText(val);
        data2.setSelectedItem(jobid);
        Specialtiesid = (int) jTable1.getModel().getValueAt(row, 0);
        btnSave.setEnabled(false);
        btnedite.setEnabled(true);
        btndelete.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnediteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnediteActionPerformed
        // TODO add your handling code here:
        if (jTextField1.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "ادخل التخصص", "خطأ", JOptionPane.ERROR_MESSAGE);
        } else {
            Edite_Data();
        }

    }//GEN-LAST:event_btnediteActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        Delete_Data();
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnnewActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        obj = null;
        Specialties.getObj().dispose();
    }//GEN-LAST:event_formWindowClosed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        int index = jComboBox1.getSelectedIndex();
        jComboBox2.setSelectedIndex(index);

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        int index = jComboBox2.getSelectedIndex();
        jComboBox1.setSelectedIndex(index);
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Specialties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Specialties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Specialties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Specialties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Specialties().setVisible(true);
            }
        });
    }

    private void fillcombobox() {
        String sql1 = "Select ID,JOB_NAME ,I from JOBS Where I=0";
        ResultSet rs = Data.Get_Data(sql1);

        try {

            while (rs.next()) {
                data.addElement(rs.getString("JOB_NAME"));
                data2.addElement(rs.getString("ID"));

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
        jComboBox1.setModel(data);
        jComboBox2.setModel(data2);
    }

    private void refrishtable() {
        jTable1.setModel(DbUtils.resultSetToTableModel(Data.Get_Data(Query)));
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setCellRenderer(rightRenderer);
        }
        ((DefaultTableCellRenderer) jTable1.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.RIGHT);
        jTable1.removeColumn(jTable1.getColumnModel().getColumn(1));
    }

    public void Save_Data() {
        try {
            String sql1 = "Select ID,Special_name ,I from Specialties "
                    + "where Special_name= '" + jTextField1.getText() + "' and Job_id = '"+data2.getSelectedItem()+"'";

            ResultSet rs = Data.Get_Data(sql1);

            if (rs.next()) {
                if (rs.getInt("I") == 0) {
                    JOptionPane.showMessageDialog(this, "التخصص موجود من قبل", "خطأ", JOptionPane.ERROR_MESSAGE);
                    jTextField1.setText("");
                    jTextField1.requestFocus();
                } else {
                    try {
                        int P = JOptionPane.showConfirmDialog(this, "التخصص محذوف هل تريد استعادته", "تأكيد", JOptionPane.YES_NO_OPTION);
                        if (P == 0) {
                            String sql = "update Specialties set I='" + 0 + "' where ID='" + rs.getInt("ID") + "'";
                            int i = Data.Save_Data(sql);
                            if (i == 0) {
                                JOptionPane.showMessageDialog(this, "تم استعادة التخصص", "استعادة تخصص", JOptionPane.INFORMATION_MESSAGE);
                                btnSave.setEnabled(true);
                                btnedite.setEnabled(false);
                                btndelete.setEnabled(false);
                                refrishtable();
                            }

                        }

                    } catch (HeadlessException | SQLException ex) {
                        JOptionPane.showMessageDialog(this, ex);
                    }

                }

            } else {
                String sql = "insert into Specialties (JOB_id,Special_name,I)values('"+data2.getSelectedItem()+"','" + jTextField1.getText() + "','" + 0 + "')";
                int i = Data.Save_Data(sql);
                if (i == 0) {
                    JOptionPane.showMessageDialog(this, "تم الحفظ بنجاح", "اضافة تخصص", JOptionPane.INFORMATION_MESSAGE);
                    refrishtable();
                    btnSave.setEnabled(false);
                }

            }

        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }

    private void reset() {
        btnSave.setEnabled(true);
        btnedite.setEnabled(false);
        btndelete.setEnabled(false);
        jTextField1.setText("");
        Specialtiesid = 0;
        refrishtable();

    }

    public void Edite_Data() {
        try {

            String sql1 = "Select ID,Special_name ,I from Specialties "
                    + "where Special_name= '" + jTextField1.getText() + "' and Job_id = '"+data2.getSelectedItem()+"'";
            ResultSet rs = Data.Get_Data(sql1);
            if (rs.next()) {
                if (rs.getInt("I") == 0) {
                    JOptionPane.showMessageDialog(this, "التخصص موجود من قبل", "خطأ", JOptionPane.ERROR_MESSAGE);
                    jTextField1.requestDefaultFocus();
                } else {
                    int t = JOptionPane.showConfirmDialog(this, "التخصص محذوف هل تريد استعادته", "تأكيد", JOptionPane.YES_NO_OPTION);
                    if (t == 0) {
                        String sql = "update Specialties set I='" + 0 + "' where ID='" + rs.getInt("ID") + "'";
                        int i = Data.Save_Data(sql);
                        if (i == 0) {
                            JOptionPane.showMessageDialog(this, "تم استعادة التخصص", "استعادة تخصص", JOptionPane.INFORMATION_MESSAGE);
                            btnSave.setEnabled(true);
                            btnedite.setEnabled(false);
                            btndelete.setEnabled(false);
                            refrishtable();
                        }

                    }

                }

            } else {

                int P = JOptionPane.showConfirmDialog(this, "هل تريد تعديل التخصص", "تأكيد", JOptionPane.YES_NO_OPTION);
                if (P == 0) {
                    String sql = "update Specialties set Special_name='" + jTextField1.getText() + "',"
                            + " Job_id = '"+ data2.getSelectedItem() +"' where ID='" + Specialtiesid + "'";
                    int i = Data.Save_Data(sql);
                    if (i == 0) {
                        JOptionPane.showMessageDialog(this, "تم التعديل بنجاح", "تعديل تخصص", JOptionPane.INFORMATION_MESSAGE);
                        reset();
                    }
                }
            }

        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }

    }

    public void Delete_Data() {
        try {
            int P = JOptionPane.showConfirmDialog(this, "سيتم حذف التخصص ولن تتمكن من استعادته", "تأكيد", JOptionPane.YES_NO_OPTION);
            if (P == 0) {
                Connection con = DatabaseConnection.con();
                PreparedStatement pst = null;

                String sql = "update Specialties set I='" + 1 + "' where ID='" + Specialtiesid + "'";

                pst = con.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(this, "تم الحذف بنجاح", "حذف تخصص", JOptionPane.INFORMATION_MESSAGE);
                btnSave.setEnabled(true);
                btnedite.setEnabled(false);
                btndelete.setEnabled(false);
                refrishtable();
            }

        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedite;
    private javax.swing.JButton btnnew;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
